---
# For jruby / torquebox:
database_url: 'jdbc:postgresql:asm_dev?user=orion&password=Password123$'
# for MRI ruby:
#database_url: 'postgres://orion:Password123$@localhost/asm_dev'
base_dir: '/opt/Dell/ASM/deployments'
logger: "require 'torquebox/logger'; TorqueBox::Logger.new"
#logger: "require 'logger' && Torquebox::Logger.new('/opt/Dell/ASM/deployments/asm_puppet.log')"
